openapi: 3.0.0
info:
  title: Appointment Creation API
  version: 1.0.5
  description: An API to create appointments based on assistant input
servers:
  - url: https://mydaygpt.com/api
    description: Base server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
  schemas:
    DateTimeResponse:
      type: object
      properties:
        currentDateTime:
          type: string
          format: date-time
          description: The current date and time in ISO 8601 format in UTC timezone.
    AppointmentRequest:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          description: The start time of the appointment as ISO8601 String in the users current or selected time zone.
        endTime:
          type: string
          format: date-time
          description: The end time of the appointment as ISO8601 String in the users current or selected time zone.
        reminderTime:
          type: string
          format: date-time
          description: The optional time for the reminder of the appointment as ISO8601 String in the users current or selected
            time zone.
        timeZone:
          type: string
          description: The timezone of the appointment as IANA time zone identifier, e.g. "Europe/Bucharest" for GMT+03:00
        title:
          type: string
          description: Some kind of title and/or occasion for the appointment as reference
        location:
          type: string
          description: The location of the appointment as free text, may include city name, street, zip code, etc.
        sender:
          type: string
          description: The originator of the appointment, either clear name or mail address
        mail:
          type: string
          format: email
          description: The email address of the recipient.
      required:
        - startTime
        - endTime
        - timeZone
        - location
        - mail
paths:
  /myday:
    get:
      summary: Get the current date and time
      operationId: getCurrentDateTime
      description: Get the current date and time in ISO8601 format
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateTimeResponse"
        "401":
          description: Unauthorized, invalid or missing API key.
        "500":
          description: Internal server error.
    post:
      summary: Create an appointment
      operationId: createAppointment
      description: Creates a new appointment with the specified details.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentRequest"
      responses:
        "200":
          description: Appointment created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Invalid input provided.
        "401":
          description: Unauthorized, invalid or missing API key.
        "500":
          description: Internal server error.
